local syntax = require "core.syntax"

syntax.add {
  files = { "%.f77$", "%.f$", "%.f90$" },
  comment = "!",
  patterns = {
    { pattern = "!.-\n",                    type = "comment"   },
    { pattern = { "'", "'", '"', '"' },     type = "string"    },
    { pattern = "-?0x%x+",                  type = "number"    },
    { pattern = "-?%d+[%d%.eE]*f?",         type = "number"    },
    { pattern = "-?%.?%d+f?",               type = "number"    },
    { pattern = "[%+%-=/%*%^%%<>!~|&]",     type = "operator"  },
    { pattern = ".true",                    type = "literal"   },
    { pattern = ".false",                   type = "literal"   },
    { pattern = ".and",                    type = "operator"  },
    { pattern = ".or",                     type = "operator"  },
    { pattern = ".not",                    type = "operator"  },
    { pattern = ".eq",                     type = "operator"  },
    { pattern = ".ne",                     type = "operator"  },
    { pattern = "[%a_][%w_]*",              type = "symbol"    },
  },
  symbols = {
    ["if"]          = "keyword",
    ["then"]        = "keyword",
    ["else"]        = "keyword",
    ["else if"]     = "keyword",
    ["do"]          = "keyword",
    ["end"]         = "keyword",
    ["for"]         = "keyword",
    ["while"]         = "keyword",
    ["return"]      = "keyword",
    ["return"]      = "keyword",
    ["goto"]        = "keyword",
    ["intent"]      = "keyword",
    ["kind"]        = "keyword",
    ["program"]     = "keyword",
    ["function"]    = "keyword",
    ["subroutine"]  = "keyword",
    ["call"]        = "keyword",
    ["read"]        = "keyword",
    ["print"]       = "keyword",
    ["write"]       = "keyword",
    ["external"]    = "keyword",
    ["include"]     = "keyword",
    ["len"]     = "keyword",
    ["character"]   = "keyword2",
    ["implicit"]    = "keyword2",
    ["logical"]     = "keyword2",
    ["complex"]     = "keyword2",
    ["double"]      = "keyword2",
    ["integer"]     = "keyword2",
    ["real"]        = "keyword2",
    ["string"]      = "keyword2",
    ["float"]       = "keyword2",
    ["double"]      = "keyword2",
    ["char"]        = "keyword2",
    ["unsigned"]    = "keyword2",
    ["bool"]        = "keyword2",
    ["null"]        = "literal",
  },
}

