local syntax = require "core.syntax"

syntax.add {
  files = { "%.tcl$" },
  comment = "#",
  patterns = {
    { pattern = "#.-\n",                    type = "comment"   },
    { pattern = { "'", "'" },               type = "string"    },
    { pattern = { '"', '"' },               type = "string"    },
    { pattern = "-?0x%x+",                  type = "number"    },
    { pattern = "-?%d+[%d%.eE]*f?",         type = "number"    },
    { pattern = "-?%.?%d+f?",               type = "number"    },
    { pattern = "-[%a_][%w_]*",             type = "operator" },
    { pattern = "[%+%-=/%*%^%%<>!~|&]",     type = "operator"  },
    { pattern = "[%a_][%w_]*",              type = "symbol"    },
  },
  symbols = {
    ["package"]     = "keyword",
    ["require"]     = "keyword",
    ["proc"]        = "keyword",
    ["if"]          = "keyword",
    ["else"]        = "keyword",
    ["elseif"]      = "keyword",
    ["while"]       = "keyword",
    ["for"]         = "keyword",
    ["foreach"]     = "keyword",
    ["return"]      = "keyword",
    ["break"]       = "keyword",
    ["continue"]    = "keyword",
    ["namespace"]   = "keyword",
    ["dict"]        = "keyword",
    ["create"]      = "keyword",
    ["catch"]       = "keyword",
    ["stdout"]       = "keyword",
    ["stdin"]       = "keyword",

    ["error"]       = "keyword2",
    ["set"]         = "keyword2",
    ["compare"]     = "keyword2",
    ["first"]       = "keyword2",
    ["list"]        = "keyword2",
    ["index"]       = "keyword2",
    ["last"]        = "keyword2",
    ["expr"]        = "keyword2",
    ["eval"]        = "keyword2",
    ["command"]     = "keyword2",
    ["configure"]   = "keyword2",
    ["cascade"]     = "keyword2",
    ["option"]      = "keyword2",
    ["array"]       = "keyword2",
    ["add"]         = "keyword2",
    ["length"]      = "keyword2",
    ["llength"]     = "keyword2",
    ["range"]       = "keyword2",
    ["match"]       = "keyword2",
    ["pattern"]     = "keyword2",
    ["tolower"]     = "keyword2",
    ["toupper"]     = "keyword2",
    ["trim"]        = "keyword2",
    ["trimleft"]    = "keyword2",
    ["trimright"]   = "keyword2",
    ["wordend"]     = "keyword2",
    ["wordstart"]   = "keyword2",
    ["open"]        = "keyword2",
    ["close"]       = "keyword2",
    ["puts"]        = "keyword2",
    ["flush"]       = "keyword2",

    -- Tk
    ["grid"]        = "keyword2",
    ["frame"]       = "keyword2",
    ["pack"]        = "keyword2",
    ["place"]       = "keyword2",
    ["bind"]        = "keyword2",

    ["button"]      = "keyword2",
    ["button"]      = "keyword2",
    ["label"]       = "keyword2",
    ["text"]        = "keyword2",
    ["message"]     = "keyword2",
    ["entry"]       = "keyword2",
    ["toplevel"]    = "keyword2",

    ["radiobutton"]  = "keyword2",
    ["checkbutton"]  = "keyword2",
    ["menu"]         = "keyword2",
    ["listbox"]      = "keyword2",
    ["canvas"]       = "keyword2",
    ["itemconfigure"] = "keyword2",
    ["selection"]     = "keyword2",
    ["curselection"]  = "keyword2",
    ["separator"]     = "keyword2",

    ["line"]         = "keyword2",
    ["arc"]          = "keyword2",
    ["oval"]         = "keyword2",
    ["rectangle"]    = "keyword2",
    ["polygon"]      = "keyword2",
    ["text"]         = "keyword2",
    ["bitmap"]       = "keyword2",
    ["image"]        = "keyword2",

    ["dialog"]       = "keyword2",
    ["spinbox"]      = "keyword2",
    ["combobox"]     = "keyword2",
    ["notebook"]     = "keyword2",
    ["button"]       = "keyword2",
    ["progressbar"]  = "keyword2",
    ["treeview"]     = "keyword2",
    ["scrollbar"]    = "keyword2",
    ["scale"]        = "keyword2",
    ["font"]         = "keyword2",

    ["wm"]           = "keyword2",
    ["title"]        = "keyword2",
    ["geometry"]     = "keyword2",
  },
}

